/* Shared deterministic core. Exact arithmetic stays out of Jev. */
globalThis.BB=(()=>{const QUESTION_PACK_VERSION="bb-ios-0.3.0",mean=a=>a.reduce((s,x)=>s+x,0)/a.length,round=(x,n=2)=>Number.isFinite(x)?+x.toFixed(n):null;
function ema(a,p){if(a.length<p)return null;let x=mean(a.slice(0,p)),k=2/(p+1);for(const v of a.slice(p))x=v*k+x*(1-k);return x}
function rsi(a,p=14){if(a.length<=p)return null;let g=0,l=0;for(let i=a.length-p;i<a.length;i++){const d=a[i]-a[i-1];d>0?g+=d:l-=d}return l?100-100/(1+(g/p)/(l/p)):100}
function sd(a){if(a.length<2)return null;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function ticker(asset,s){s=s.toUpperCase().trim().replace(/[\/-]/g,"");if(asset==="forex"&&!s.startsWith("C:"))return"C:"+s;if(asset==="crypto"&&!s.startsWith("X:"))return"X:"+s;return s}
function features(rows,asset,span,mult,plan={}){const c=rows.map(x=>x.c),last=c.at(-1),prev=c.at(-2),rets=c.slice(1).map((x,i)=>Math.log(x/c[i])),periods=span==="day"?(asset==="stocks"?252:365):span==="hour"?24*365:365*24*60/+mult,rr=plan.entry&&plan.stop&&plan.target&&plan.entry!==plan.stop?Math.abs(plan.target-plan.entry)/Math.abs(plan.entry-plan.stop):null,vol=rows.map(x=>x.v||0),v20=vol.length>=20?mean(vol.slice(-20)):null,v5=vol.length>=5?mean(vol.slice(-5)):null,hi=Math.max(...rows.slice(-20).map(x=>x.h)),lo=Math.min(...rows.slice(-20).map(x=>x.l)),range=hi-lo;
return{last:round(last),changePct:round((last/prev-1)*100),sma20:round(mean(c.slice(-20))),sma50:c.length>=50?round(mean(c.slice(-50))):null,ema20:round(ema(c,20)),rsi14:round(rsi(c)),annualizedVolPct:round(sd(rets.slice(-Math.min(30,rets.length)))*Math.sqrt(periods)*100),trend20Pct:c.length>=20?round((last/c.at(-20)-1)*100):null,high20:round(hi),low20:round(lo),rangePosition20:range?round((last-lo)/range*100):null,volumeRatio5v20:v20?round(v5/v20):null,rewardRisk:round(rr)}}
function questions(){return{
direction_bias:{type:"choice",instructions:"Using only supplied observed/calculated facts, identify the best-supported directional regime for the selected horizon. Use uncertain when evidence is insufficient or materially conflicting.",criteria:{rise:"Upward movement is best supported.",fall:"Downward movement is best supported.",sideways:"Range-bound/directionless movement is best supported.",uncertain:"Evidence is insufficient or materially conflicting."}},
rise_supported:{type:"noul",instructions:"Does the supplied evidence support upward price movement over the selected horizon?"},
fall_supported:{type:"noul",instructions:"Does the supplied evidence support downward price movement over the selected horizon?"},
trend_regime:{type:"choice",instructions:"Classify the trend regime from supplied price, moving-average and trend facts.",criteria:{bullish:"Persistent upward structure.",bearish:"Persistent downward structure.",range:"Predominantly range-bound structure.",transition:"Evidence suggests a regime transition.",uncertain:"Insufficient/conflicting evidence."}},
momentum_regime:{type:"choice",instructions:"Classify momentum using supplied RSI, returns and price-position facts.",criteria:{strong_positive:"Strong positive momentum.",positive:"Positive momentum.",neutral:"Neutral momentum.",negative:"Negative momentum.",strong_negative:"Strong negative momentum.",uncertain:"Insufficient/conflicting evidence."}},
volatility_regime:{type:"choice",instructions:"Classify volatility relative to the supplied recent market evidence.",criteria:{compressed:"Unusually compressed.",normal:"Neither notably compressed nor elevated.",elevated:"Meaningfully elevated.",extreme:"Extreme/unstable.",uncertain:"Insufficient evidence."}},
liquidity_quality:{type:"score",instructions:"Judge observable execution/liquidity quality only from supplied quote, spread, trade and volume evidence. Do not infer missing liquidity data.",criteria:["Very poor: severe or unknown execution conditions.","Weak: thin activity or wide/unstable spread evidence.","Usable: adequate but imperfect execution conditions.","Strong: healthy activity and generally efficient spread evidence.","Very strong: deep, active and consistently efficient observable conditions."]},
setup_risk:{type:"score",instructions:"Judge setup risk from volatility, range, liquidity, trend consistency and optional trade plan. Score only supplied evidence.",criteria:["Low: stable, coherent and well-bounded.","Moderate-low: some uncertainty but mostly bounded.","Moderate: meaningful uncertainty/volatility/conflict.","High: substantial instability, conflicts or poorly bounded risk.","Very high: extreme/unstable or too incomplete to bound responsibly."]},
evidence_quality:{type:"score",instructions:"Judge completeness, freshness, relevance and internal consistency of supplied evidence.",criteria:["Very poor: critical evidence missing/stale/contradictory.","Weak: important gaps or conflicts.","Usable: sufficient for tentative judgment.","Strong: broad fresh evidence with limited conflicts.","Very strong: unusually complete, fresh and mutually consistent evidence."]},
signals_conflicting:{type:"noul",instructions:"Do supplied trend, momentum, volatility, liquidity and price-position facts materially conflict?"},
breakout_supported:{type:"noul",instructions:"Does supplied evidence support a genuine breakout or breakdown rather than ordinary range movement?"},
mean_reversion_supported:{type:"noul",instructions:"Does supplied evidence support mean reversion toward the recent range/average?"},
setup_attractive:{type:"noul",instructions:"Considering only supplied evidence and optional trade plan, is the setup attractive on a risk-versus-evidence basis?"},
trade_plan_quality:{type:"score",instructions:"If entry/stop/target are supplied, judge plan structure using reward/risk, market structure and volatility. If absent, use the lowest-information criterion.",criteria:["Not assessable/poor: absent or structurally weak plan.","Weak: unfavorable or poorly aligned risk boundaries.","Usable: coherent plan with meaningful caveats.","Strong: favorable, well-bounded and structure-aware plan.","Very strong: unusually coherent risk/reward and market-structure alignment."]}}}
return{QUESTION_PACK_VERSION,ticker,features,questions,round}})();