/* Shared deterministic core. Exact arithmetic stays out of Jev. */
globalThis.BB=(()=>{const QUESTION_PACK_VERSION="bb-ios-0.3.0",mean=a=>a.reduce((s,x)=>s+x,0)/a.length,round=(x,n=2)=>Number.isFinite(x)?+x.toFixed(n):null;
function ema(a,p){if(a.length<p)return null;let x=mean(a.slice(0,p)),k=2/(p+1);for(const v of a.slice(p))x=v*k+x*(1-k);return x}
function rsi(a,p=14){if(a.length<=p)return null;let g=0,l=0;for(let i=a.length-p;i<a.length;i++){const d=a[i]-a[i-1];d>0?g+=d:l-=d}return l?100-100/(1+(g/p)/(l/p)):100}
function sd(a){if(a.length<2)return null;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function ticker(asset,s){s=s.toUpperCase().trim().replace(/[\/-]/g,"");if(asset==="forex"&&!s.startsWith("C:"))return"C:"+s;if(asset==="crypto"&&!s.startsWith("X:"))return"X:"+s;return s}
function features(rows,asset,span,mult,plan={}){const c=rows.map(x=>x.c),last=c.at(-1),prev=c.at(-2),rets=c.slice(1).map((x,i)=>Math.log(x/c[i])),periods=span==="day"?(asset==="stocks"?252:365):span==="hour"?24*365:365*24*60/+mult,rr=plan.entry&&plan.stop&&plan.target&&plan.entry!==plan.stop?Math.abs(plan.target-plan.entry)/Math.abs(plan.entry-plan.stop):null,vol=rows.map(x=>x.v||0),v20=vol.length>=20?mean(vol.slice(-20)):null,v5=vol.length>=5?mean(vol.slice(-5)):null,hi=Math.max(...rows.slice(-20).map(x=>x.h)),lo=Math.min(...rows.slice(-20).map(x=>x.l)),range=hi-lo;
return{last:round(last),changePct:round((last/prev-1)*100),sma20:round(mean(c.slice(-20))),sma50:c.length>=50?round(mean(c.slice(-50))):null,ema20:round(ema(c,20)),rsi14:round(rsi(c)),annualizedVolPct:round(sd(rets.slice(-Math.min(30,rets.length)))*Math.sqrt(periods)*100),trend20Pct:c.length>=20?round((last/c.at(-20)-1)*100):null,high20:round(hi),low20:round(lo),rangePosition20:range?round((last-lo)/range*100):null,volumeRatio5v20:v20?round(v5/v20):null,rewardRisk:round(rr)}}
const HORIZONS={
"15m":{label:"15 minutes",mult:1,span:"minute",days:3,bars:60,profile:"scalp",focus:["immediate price action","VWAP","volume acceleration","liquidity","spread/execution","micro momentum","breakout failure"]},
"1h":{label:"1 hour",mult:5,span:"minute",days:7,bars:72,profile:"intraday",focus:["intraday momentum","VWAP","volume","liquidity","volatility","near-term structure"]},
"4h":{label:"4 hours",mult:15,span:"minute",days:14,bars:80,profile:"intraday",focus:["intraday trend","momentum","volume confirmation","volatility","breakout structure"]},
"1d":{label:"1 day",mult:1,span:"hour",days:45,bars:96,profile:"swing",focus:["multi-session trend","momentum","volume","volatility","support/resistance"]},
"3d":{label:"3 days",mult:1,span:"hour",days:90,bars:120,profile:"swing",focus:["short swing trend","momentum persistence","volume confirmation","volatility regime"]},
"1w":{label:"1 week",mult:1,span:"day",days:180,bars:90,profile:"swing",focus:["daily trend","momentum persistence","volume regime","market structure","event risk"]},
"1m":{label:"1 month",mult:1,span:"day",days:365,bars:120,profile:"position",focus:["medium trend","relative price strength","volatility regime","fundamentals","corporate events"]},
"3m":{label:"3 months",mult:1,span:"day",days:730,bars:180,profile:"position",focus:["durable trend","fundamentals","earnings/corporate events","drawdown risk","regime stability"]},
"6m":{label:"6 months",mult:1,span:"day",days:1095,bars:252,profile:"investment",focus:["durable trend","fundamental quality","growth consistency","corporate actions","longer volatility"]},
"1y":{label:"1 year",mult:1,span:"day",days:1825,bars:504,profile:"investment",focus:["long-term trend","fundamental durability","growth consistency","drawdowns","business/event evidence"]},
"3y":{label:"3 years",mult:1,span:"week",days:3650,bars:260,profile:"investment",focus:["multi-year trend","fundamental durability","cycle resilience","drawdown history","structural growth"]},
"5y":{label:"5+ years",mult:1,span:"week",days:5475,bars:390,profile:"investment",focus:["structural trend","fundamental durability","cycle resilience","long-run drawdowns","persistent growth"]}};
function horizon(key){return HORIZONS[key]||HORIZONS["1w"]}
function evidenceModel(raw={},metrics={},hp={profile:"swing"}){
 const arr=x=>Array.isArray(x)?x:[],num=(o,keys)=>{for(const k of keys){const v=k.split(".").reduce((a,p)=>a?.[p],o);if(Number.isFinite(+v))return +v}return null},growth=(a,b)=>Number.isFinite(a)&&Number.isFinite(b)&&b!==0?round((a/b-1)*100):null;
 const quotes=arr(raw.quotes),trades=arr(raw.trades),news=arr(raw.news),si=arr(raw.shortInterest),fund=raw.fundamentals||{},actions=raw.corporateActions||{};
 const q=quotes[0]||{},bid=num(q,["bid_price","bid.price","bid"]),ask=num(q,["ask_price","ask.price","ask"]),mid=bid&&ask?(bid+ask)/2:null,spread=mid?round((ask-bid)/mid*10000):null;
 const inc=arr(fund.income),cash=arr(fund.cashFlow),bal=arr(fund.balanceSheet),rat=arr(fund.ratios);
 const rev=inc.map(x=>num(x,["revenues.value","revenue","revenues","financials.income_statement.revenues.value"])).filter(Number.isFinite);
 const ni=inc.map(x=>num(x,["net_income_loss.value","net_income","financials.income_statement.net_income_loss.value"])).filter(Number.isFinite);
 const fcf=cash.map(x=>num(x,["free_cash_flow","net_cash_flow_from_operating_activities.value","financials.cash_flow_statement.net_cash_flow_from_operating_activities.value"])).filter(Number.isFinite);
 const debt=bal.map(x=>num(x,["liabilities.value","total_liabilities","financials.balance_sheet.liabilities.value"])).filter(Number.isFinite);
 const ratio=rat[0]||{};
 return{profile:hp.profile,market:{last:metrics.last,changePct:metrics.changePct,rsi14:metrics.rsi14,trend20Pct:metrics.trend20Pct,annualizedVolPct:metrics.annualizedVolPct,rangePosition20:metrics.rangePosition20,volumeRatio5v20:metrics.volumeRatio5v20},execution:{quoteCount:quotes.length,tradeSampleCount:trades.length,bid,ask,spreadBps:spread},fundamentals:{periods:inc.length,revenueLatest:rev[0]??null,revenueGrowthPct:rev.length>1?growth(rev[0],rev[1]):null,netIncomeLatest:ni[0]??null,netIncomeGrowthPct:ni.length>1?growth(ni[0],ni[1]):null,cashFlowLatest:fcf[0]??null,cashFlowGrowthPct:fcf.length>1?growth(fcf[0],fcf[1]):null,liabilitiesLatest:debt[0]??null,pe:num(ratio,["price_to_earnings_ratio","pe_ratio"]),priceToBook:num(ratio,["price_to_book_ratio","pb_ratio"]),debtToEquity:num(ratio,["debt_to_equity_ratio"])},context:{newsItems:news.length,shortInterestPeriods:si.length,dividendRecords:arr(actions.dividends).length,splitRecords:arr(actions.splits).length},availability:{quotes:!raw.quotes?false:!raw.quotes._unavailable,trades:!raw.trades?false:!raw.trades._unavailable,company:!!raw.company&&!raw.company._unavailable,news:!!raw.news&&!raw.news._unavailable,fundamentals:!!raw.fundamentals,corporateActions:!!raw.corporateActions}};
}
function questions(h="1w"){const x=horizon(h),q={
direction_bias:{type:"choice",instructions:"Using only supplied observed/calculated facts, identify the best-supported directional regime for the selected horizon. Use uncertain when evidence is insufficient or materially conflicting.",criteria:{rise:"Upward movement is best supported.",fall:"Downward movement is best supported.",sideways:"Range-bound/directionless movement is best supported.",uncertain:"Evidence is insufficient or materially conflicting."}},
rise_supported:{type:"noul",instructions:"Does the supplied evidence support upward price movement over the selected horizon?"},
fall_supported:{type:"noul",instructions:"Does the supplied evidence support downward price movement over the selected horizon?"},
trend_regime:{type:"choice",instructions:"Classify the trend regime from supplied price, moving-average and trend facts.",criteria:{bullish:"Persistent upward structure.",bearish:"Persistent downward structure.",range:"Predominantly range-bound structure.",transition:"Evidence suggests a regime transition.",uncertain:"Insufficient/conflicting evidence."}},
momentum_regime:{type:"choice",instructions:"Classify momentum using supplied RSI, returns and price-position facts.",criteria:{strong_positive:"Strong positive momentum.",positive:"Positive momentum.",neutral:"Neutral momentum.",negative:"Negative momentum.",strong_negative:"Strong negative momentum.",uncertain:"Insufficient/conflicting evidence."}},
volatility_regime:{type:"choice",instructions:"Classify volatility relative to the supplied recent market evidence.",criteria:{compressed:"Unusually compressed.",normal:"Neither notably compressed nor elevated.",elevated:"Meaningfully elevated.",extreme:"Extreme/unstable.",uncertain:"Insufficient evidence."}},
liquidity_quality:{type:"score",instructions:"Judge observable execution/liquidity quality only from supplied quote, spread, trade and volume evidence. Do not infer missing liquidity data.",criteria:["Very poor: severe or unknown execution conditions.","Weak: thin activity or wide/unstable spread evidence.","Usable: adequate but imperfect execution conditions.","Strong: healthy activity and generally efficient spread evidence.","Very strong: deep, active and consistently efficient observable conditions."]},
setup_risk:{type:"score",instructions:"Judge setup risk from volatility, range, liquidity, trend consistency and optional trade plan. Score only supplied evidence.",criteria:["Low: stable, coherent and well-bounded.","Moderate-low: some uncertainty but mostly bounded.","Moderate: meaningful uncertainty/volatility/conflict.","High: substantial instability, conflicts or poorly bounded risk.","Very high: extreme/unstable or too incomplete to bound responsibly."]},
evidence_quality:{type:"score",instructions:"Judge completeness, freshness, relevance and internal consistency of supplied evidence.",criteria:["Very poor: critical evidence missing/stale/contradictory.","Weak: important gaps or conflicts.","Usable: sufficient for tentative judgment.","Strong: broad fresh evidence with limited conflicts.","Very strong: unusually complete, fresh and mutually consistent evidence."]},
signals_conflicting:{type:"noul",instructions:"Do supplied trend, momentum, volatility, liquidity and price-position facts materially conflict?"},
breakout_supported:{type:"noul",instructions:"Does supplied evidence support a genuine breakout or breakdown rather than ordinary range movement?"},
mean_reversion_supported:{type:"noul",instructions:"Does supplied evidence support mean reversion toward the recent range/average?"},
setup_attractive:{type:"noul",instructions:"Considering only supplied evidence and optional trade plan, is the setup attractive on a risk-versus-evidence basis?"},
trade_plan_quality:{type:"score",instructions:"If entry/stop/target are supplied, judge plan structure using reward/risk, market structure and volatility. If absent, use the lowest-information criterion.",criteria:["Not assessable/poor: absent or structurally weak plan.","Weak: unfavorable or poorly aligned risk boundaries.","Usable: coherent plan with meaningful caveats.","Strong: favorable, well-bounded and structure-aware plan.","Very strong: unusually coherent risk/reward and market-structure alignment."]}};
const suffix=` Evaluate specifically for a ${x.label} holding horizon. Prioritize: ${x.focus.join(", ")}.`;for(const v of Object.values(q))v.instructions+=suffix;
if(x.profile==="investment"){delete q.breakout_supported;delete q.mean_reversion_supported;q.durable_growth={type:"noul",instructions:"Does supplied long-horizon evidence support durable growth or appreciation rather than a temporary move?"+suffix};q.long_horizon_resilience={type:"score",instructions:"Judge resilience of the long-horizon thesis to volatility, drawdowns, changing regimes and supplied fundamental/event evidence."+suffix,criteria:["Very weak resilience.","Weak resilience.","Moderate resilience.","Strong resilience.","Very strong resilience."]}}
return q}
return{QUESTION_PACK_VERSION,HORIZONS,horizon,ticker,features,evidenceModel,questions,round}})();