/* Shared deterministic core. Exact arithmetic stays out of Jev. */
globalThis.BB=(()=>{const mean=a=>a.reduce((s,x)=>s+x,0)/a.length,round=(x,n=2)=>Number.isFinite(x)?+x.toFixed(n):null;
function ema(a,p){if(a.length<p)return null;let x=mean(a.slice(0,p)),k=2/(p+1);for(const v of a.slice(p))x=v*k+x*(1-k);return x}
function rsi(a,p=14){if(a.length<=p)return null;let g=0,l=0;for(let i=a.length-p;i<a.length;i++){const d=a[i]-a[i-1];d>0?g+=d:l-=d}return l?100-100/(1+(g/p)/(l/p)):100}
function sd(a){if(a.length<2)return null;const m=mean(a);return Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/(a.length-1))}
function ticker(asset,s){s=s.toUpperCase().trim().replace(/[\/-]/g,"");if(asset==="forex"&&!s.startsWith("C:"))return"C:"+s;if(asset==="crypto"&&!s.startsWith("X:"))return"X:"+s;return s}
function features(rows,asset,span,mult,plan={}){const c=rows.map(x=>x.c),last=c.at(-1),prev=c.at(-2),rets=c.slice(1).map((x,i)=>Math.log(x/c[i])),periods=span==="day"?(asset==="stocks"?252:365):span==="hour"?24*365:365*24*60/+mult,rr=plan.entry&&plan.stop&&plan.target&&plan.entry!==plan.stop?Math.abs(plan.target-plan.entry)/Math.abs(plan.entry-plan.stop):null;return{last:round(last),changePct:round((last/prev-1)*100),sma20:round(mean(c.slice(-20))),sma50:c.length>=50?round(mean(c.slice(-50))):null,ema20:round(ema(c,20)),rsi14:round(rsi(c)),annualizedVolPct:round(sd(rets.slice(-Math.min(30,rets.length)))*Math.sqrt(periods)*100),trend20Pct:round((last/c.at(-20)-1)*100),high20:round(Math.max(...rows.slice(-20).map(x=>x.h))),low20:round(Math.min(...rows.slice(-20).map(x=>x.l))),rewardRisk:round(rr)}}
function questions(){return{
direction_bias:{type:"choice",instructions:"Given only the observed market facts in state, which directional condition is best supported for the selected timeframe? Choose uncertain when evidence is insufficient or materially conflicting.",criteria:{rise:"Evidence favors upward price movement.",fall:"Evidence favors downward price movement.",sideways:"Evidence favors range-bound or directionless movement.",uncertain:"Evidence is insufficient or materially conflicting."}},
rise_supported:{type:"noul",instructions:"Given only the observed market facts in state, is evidence for upward price movement over the selected timeframe stronger than evidence against it?"},
fall_supported:{type:"noul",instructions:"Given only the observed market facts in state, is evidence for downward price movement over the selected timeframe stronger than evidence against it?"},
setup_risk:{type:"score",instructions:"Judge the degree of market/setup risk shown by volatility, range, trend consistency and the optional trade plan. Score only supplied evidence.",criteria:["Low: stable conditions and a well-bounded setup with little conflicting evidence.","Moderate-low: some uncertainty or volatility, but risk remains mostly bounded.","Moderate: meaningful uncertainty, volatility or conflicting signals require caution.","High: strong volatility, weak structure, substantial conflicts or poorly bounded trade risk.","Very high: extreme or unstable conditions, or evidence is too incomplete to bound risk responsibly."]},
evidence_quality:{type:"score",instructions:"Judge how complete and internally consistent the supplied evidence is for a directional market assessment.",criteria:["Very poor: key evidence is missing or contradictory.","Weak: limited evidence with important gaps or conflicts.","Usable: enough evidence for a tentative judgment, with meaningful uncertainty.","Strong: broad relevant evidence with limited conflicts.","Very strong: unusually complete, relevant and mutually consistent evidence."]},
signals_conflicting:{type:"noul",instructions:"Do the supplied trend, momentum, volatility and price-position facts materially conflict with one another?"}}}
return{ticker,features,questions,round}})();