const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],M="https://api.massive.com",J="https://api.typesafe.ai/v1/systemone";const iso=n=>new Date(Date.now()-n*864e5).toISOString().slice(0,10),pct=x=>Number.isFinite(+x)?Math.round(+x*100)+"%":"—",fmt=x=>Number.isFinite(+x)?(+x).toFixed(2):"—";
async function api(url,key){const r=await fetch(url+(url.includes("?")?"&":"?")+"apiKey="+encodeURIComponent(key)),t=await r.text();if(!r.ok)throw Error("Massive "+r.status+": "+t.slice(0,140));return JSON.parse(t)}
async function optional(url,key){try{return await api(url,key)}catch(e){return{_unavailable:true,reason:String(e.message||e).slice(0,180)}}}
async function horizonEvidence(asset,ticker,hp,key){
 const ev={profile:hp.profile};
 if(asset!=="stocks")return ev;
 if(hp.profile==="scalp"||hp.profile==="intraday"){
  const [q,t]=await Promise.all([optional(`${M}/v3/quotes/${encodeURIComponent(ticker)}?order=desc&limit=50&sort=sip_timestamp`,key),optional(`${M}/v3/trades/${encodeURIComponent(ticker)}?order=desc&limit=50&sort=timestamp`,key)]);
  ev.quotes=q.results||q;ev.trades=t.results||t;
 }else{
  const [details,news,shorts]=await Promise.all([optional(`${M}/v3/reference/tickers/${encodeURIComponent(ticker)}`,key),optional(`${M}/v2/reference/news?ticker=${encodeURIComponent(ticker)}&order=desc&limit=10&sort=published_utc`,key),optional(`${M}/stocks/v1/short-interest?ticker=${encodeURIComponent(ticker)}&limit=4&sort=settlement_date.desc`,key)]);
  ev.company=details.results||details;ev.news=news.results||news;ev.shortInterest=shorts.results||shorts;
  if(hp.profile==="investment"||hp.profile==="position"){
   const [ratios,income,cash,balance,dividends,splits]=await Promise.all([
    optional(`${M}/stocks/financials/v1/ratios?ticker=${encodeURIComponent(ticker)}&limit=4`,key),
    optional(`${M}/stocks/financials/v1/income-statements?tickers=${encodeURIComponent(ticker)}&limit=8`,key),
    optional(`${M}/stocks/financials/v1/cash-flow-statements?tickers=${encodeURIComponent(ticker)}&limit=8`,key),
    optional(`${M}/stocks/financials/v1/balance-sheets?tickers=${encodeURIComponent(ticker)}&limit=8`,key),
    optional(`${M}/stocks/v1/dividends?ticker=${encodeURIComponent(ticker)}&limit=20&sort=ex_dividend_date.desc`,key),
    optional(`${M}/stocks/v1/splits?ticker=${encodeURIComponent(ticker)}&limit=10&sort=execution_date.desc`,key)]);
   ev.fundamentals={ratios:ratios.results||ratios,income:income.results||income,cashFlow:cash.results||cash,balanceSheet:balance.results||balance};
   ev.corporateActions={dividends:dividends.results||dividends,splits:splits.results||splits};
  }
 }
 return ev;
}
async function jev(body,key){const r=await fetch(J,{method:"POST",headers:{Authorization:"Bearer "+key,"Content-Type":"application/json"},body:JSON.stringify(body)}),t=await r.text();if(!r.ok)throw Error("Jev "+r.status+": "+t.slice(0,140));return JSON.parse(t)}
$$("nav button").forEach(b=>b.onclick=()=>{$$("nav button").forEach(x=>x.classList.toggle("active",x===b));$$(".tab").forEach(x=>x.classList.toggle("hidden",x.id!==b.dataset.tab))});
(async()=>{const x=await chrome.storage.local.get(["massiveKey","jevKey","jevModel"]);$("#massiveKey").value=x.massiveKey||"";$("#jevKey").value=x.jevKey||"";$("#jevModel").value=x.jevModel||"jev-latest"})();
$("#save").onclick=async()=>{await chrome.storage.local.set({massiveKey:$("#massiveKey").value.trim(),jevKey:$("#jevKey").value.trim(),jevModel:$("#jevModel").value.trim()||"jev-latest"});$("#status").textContent="Settings saved locally."};
$("#asset").onchange=()=>$("#symbol").value=$("#asset").value==="stocks"?"AAPL":$("#asset").value==="forex"?"EURUSD":"BTCUSD";
function syncHorizonControls(){const hp=BB.horizon($("#horizon").value);$("#timeframe").value=`${hp.mult},${hp.span}`;$("#lookback").value=String(hp.days)}
$("#horizon").onchange=syncHorizonControls;syncHorizonControls();
$("#analyse").onclick=async()=>{try{$("#analyse").disabled=true;$("#result").classList.add("hidden");const saved=await chrome.storage.local.get(["massiveKey","jevKey","jevModel"]),mk=$("#massiveKey").value.trim()||saved.massiveKey,jk=$("#jevKey").value.trim()||saved.jevKey;if(!mk||!jk)throw Error("Add both API keys in Settings.");const asset=$("#asset").value,ticker=BB.ticker(asset,$("#symbol").value),horizon=$("#horizon").value,hp=BB.horizon(horizon),[multRaw,span]=$("#timeframe").value.split(","),mult=+multRaw,days=+$("#lookback").value;$("#status").textContent="Fetching observed market data…";const data=await api(`${M}/v2/aggs/ticker/${encodeURIComponent(ticker)}/range/${mult}/${span}/${iso(days)}/${iso(0)}?adjusted=true&sort=asc&limit=5000`,mk),rows=data.results||[];if(rows.length<20)throw Error("At least 20 bars are required.");const plan={entry:+$("#entry").value||null,stop:+$("#stop").value||null,target:+$("#target").value||null},metrics=BB.features(rows,asset,span,mult,plan);let snapshot=null,indicators={};try{const s=await api(`${M}/v3/snapshot?ticker.any_of=${encodeURIComponent(ticker)}`,mk);snapshot=s.results?.[0]||null}catch{};for(const [name,path] of [["rsi","rsi"],["macd","macd"],["sma","sma"],["ema","ema"]]){try{const q=name==="rsi"?`?timespan=${span}&window=14&adjusted=true&series_type=close&order=desc&limit=1`:`?timespan=${span}&adjusted=true&series_type=close&order=desc&limit=1`;indicators[name]=(await api(`${M}/v1/indicators/${path}/${encodeURIComponent(ticker)}${q}`,mk)).results?.values?.[0]||null}catch{}}
const horizonData=await horizonEvidence(asset,ticker,hp,mk),evidence=BB.evidenceModel(horizonData,metrics,hp);const state={meta:{questionPackVersion:BB.QUESTION_PACK_VERSION,generatedAt:new Date().toISOString(),tradeHorizon:horizon,horizonProfile:hp.profile,horizonLabel:hp.label,evidenceFocus:hp.focus,evidenceWindowDays:days,horizonInstruction:`Evaluate specifically for a ${hp.label} holding period using the ${hp.profile} evidence profile. Prioritize ${hp.focus.join(", ")}. Do not extrapolate beyond supplied evidence.`},observed:{asset,symbol:ticker,timeframe:{multiplier:+mult,timespan:span},lastBarAt:new Date(rows.at(-1).t).toISOString(),barCount:rows.length,recentBars:rows.slice(-Math.min(hp.bars,120)).map(x=>({at:new Date(x.t).toISOString(),open:x.o,high:x.h,low:x.l,close:x.c,volume:x.v??null,vwap:x.vw??null})),snapshot,providerIndicators:indicators,evidence},calculated:{metrics,tradePlan:plan,evidenceModel:evidence},constraints:{instruction:"Use only supplied observed/calculated fields. Treat missing provider fields as unknown. Do not invent news, fundamentals, macro events or future facts. Provider technical indicators are corroborating observations; deterministic calculated metrics remain separately identified."}};$("#status").textContent="Requesting independent typed judgments from Jev…";const out=await jev({model:$("#jevModel").value.trim()||saved.jevModel||"jev-latest",state,questions:BB.questions(horizon)},jk);render(ticker,metrics,state,out,evidence,rows);$("#status").textContent="Complete."}catch(e){$("#status").textContent=e.message}finally{$("#analyse").disabled=false}};
const TERMS={rsi14:["Momentum (RSI)","Shows whether recent price moves have been unusually strong or weak. Around 50 is neutral; very high or low readings can signal stretched momentum."],sma20:["20-period average price","The average closing price across the latest 20 bars. It smooths short-term noise."],sma50:["50-period average price","A slower average used to understand the broader trend."],ema20:["Responsive 20-period average","Similar to an average price, but gives more weight to recent prices."],annualizedVolPct:["Price volatility","How widely price has been moving. Higher values generally mean larger swings and more uncertainty."],trend20Pct:["20-period trend","How much price has changed across the latest 20 bars."],rangePosition20:["Position in recent range","Where the current price sits between the recent low and high. 0% is near the low and 100% near the high."],volumeRatio5v20:["Recent trading activity","Compares recent volume with its longer average. Above 1 means activity has increased."],rewardRisk:["Potential reward vs risk","Compares the distance to your target with the distance to your stop. Only shown when a trade plan is entered."],last:["Latest price","The latest closing price in the evidence window."],changePct:["Latest price change","Change from the previous bar."]};
function friendly(k){return TERMS[k]?.[0]||k.replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ").replace(/^./,x=>x.toUpperCase())}
function help(k){return TERMS[k]?.[1]||""}
function drawPriceChart(rows,state){const svg=$("#priceChart");if(!svg||!rows?.length)return;const pts=rows.slice(-Math.min(rows.length,120)),vals=pts.map(x=>+x.c).filter(Number.isFinite);if(vals.length<2)return;const lo=Math.min(...vals),hi=Math.max(...vals),pad=(hi-lo||1)*.08,min=lo-pad,max=hi+pad,w=600,h=220,x=i=>28+i*(w-56)/(vals.length-1),y=v=>18+(max-v)*(h-42)/(max-min);const path=vals.map((v,i)=>(i?"L":"M")+x(i).toFixed(1)+" "+y(v).toFixed(1)).join(" ");svg.innerHTML='<line x1="28" y1="18" x2="28" y2="196" class="axis"/><line x1="28" y1="196" x2="572" y2="196" class="axis"/><path d="'+path+'" class="price-line" fill="none"/><text x="32" y="34">'+hi.toFixed(2)+'</text><text x="32" y="190">'+lo.toFixed(2)+'</text>';$("#chartCaption").textContent=state.meta.evidenceWindowDays+" days · "+state.observed.timeframe.multiplier+" "+state.observed.timeframe.timespan+" bars"}

function render(ticker,m,state,out,evidence,rows){drawPriceChart(rows,state);const a=out.answers||{},rise=a.rise_supported?.noul,fall=a.fall_supported?.noul;$("#rsym").textContent=ticker;$("#horizonBadge").textContent=(state.meta.horizonLabel+" · "+state.observed.timeframe.multiplier+" "+state.observed.timeframe.timespan+" · "+state.meta.evidenceWindowDays+"D").toUpperCase();$("#bias").textContent=(a.direction_bias?.choice||"uncertain").toUpperCase();$("#risk").textContent=Number.isFinite(+a.setup_risk?.score)?(+a.setup_risk.score).toFixed(2)+" / 4":"—";$("#rise").textContent=pct(rise);$("#fall").textContent=pct(fall);const bias=(a.direction_bias?.choice||"uncertain");const plain={rise:"The evidence currently leans upward for this time horizon.",fall:"The evidence currently leans downward for this time horizon.",sideways:"The evidence suggests price may remain mostly range-bound for this time horizon.",uncertain:"The available evidence is mixed or incomplete, so there is no clear direction."};$("#plainSummary").innerHTML=`<b>In plain English</b><p>${plain[bias]||plain.uncertain}</p><small>These are evidence-based judgments, not a guarantee of what the market will do.</small>`;const fields=[["last",m.last],["changePct",m.changePct],["rsi14",m.rsi14],["sma20",m.sma20],["sma50",m.sma50],["ema20",m.ema20],["annualizedVolPct",m.annualizedVolPct],["trend20Pct",m.trend20Pct],["rangePosition20",m.rangePosition20],["volumeRatio5v20",m.volumeRatio5v20],["rewardRisk",m.rewardRisk]];$("#metrics").innerHTML=fields.map(([k,v])=>`<div><span>${friendly(k)} <button class="info" title="${help(k)}" aria-label="${help(k)}">?</button></span><b>${fmt(v)}</b><small>${help(k)}</small></div>`).join("");$("#evidence").innerHTML=Object.entries({...evidence.execution,...evidence.fundamentals,...evidence.context}).filter(([,v])=>v!==null&&v!==false&&typeof v!=="object").map(([k,v])=>`<div><span>${k.replaceAll("_"," ")}</span><b>${typeof v==="number"?fmt(v):v}</b></div>`).join("");$("#answers").innerHTML=Object.entries(a).map(([k,v])=>`<div class="answer"><b>${k.replaceAll("_"," ")}</b>${v.type==="noul"?pct(v.noul):v.type==="choice"?v.choice+" · choice confidence "+pct(v.confidence):Number.isFinite(+v.score)?(+v.score).toFixed(2)+" / 4":"—"}</div>`).join("");$("#state").textContent=JSON.stringify(state,null,2);$("#raw").textContent=JSON.stringify(out,null,2);$("#result").classList.remove("hidden")}